### ISSUE TITLE
task6 : Create a logistic regression model

### ISSUE THREAD

**Issue by nlauchande** [omdena/ptsd#10]
Goals :
- Create a logistic regression model based in the current data available

**Target definition** :
    if sum(criterion_collumn)>=1 then criterion_labelled

Major blocker at the moment :
      - Availability training the data.

**Comment by kulsoom-abdullah** [comment]
I could not make the meeting. I would like to confirm this target definition - is this a sum across a row or a column?

**Comment by nlauchande** [comment]
Availability over a column.

**Comment by kulsoom-abdullah** [comment]
I went over Sylvia's notebook - to confirm I understand : 
Take each transcript separately and put the client speaking into one document. If any of the client conversations rows were labeled with a symptom, mark this document as having that as a label?

**Comment by nlauchande** [comment]
@kulsoom-abdullah : Just for visibility : For the initial dummy ML pipeline i am basically doing something simpler than that. I am commiting the code to this branch : 

I am picking Alexis spreadsheet and loading directly into pandas is nicely organized and then concatenating all the text and summing over the columns. I am currently trying to come up with some very basic features based on the text collumn. Still WIP but you can look at the idea on the notebook: https://github.com/omdena/ptsd/blob/ml_backend/task1_machine_learning_backend/classifcation_backend/exploring_data_pipeline.ipynb

**Comment by kulsoom-abdullah** [comment]
> @kulsoom-abdullah : Just for visibility : For the initial dummy ML pipeline i am basically doing something simpler than that. I am commiting the code to this branch : https://github.com/omdena/ptsd/blob/ml_backend/task1_machine_learning_backend/classifcation_backend/exploring_data_pipeline.ipynb
> 
> I am picking Alexis spreadsheet and loading directly into pandas. It is nicely organized and not a lot of need to parse.After that i am concatenating all the text and summing over the columns. I am currently trying to come up with some very basic features based on the text collumn.

Thanks for sharing the code.  I understand now. I will copy your code into my notebook on google colab. If it helps, I have some text processing you can use in my notebook. The link is here:
https://colab.research.google.com/drive/1uKkgcf1Q7XmUejxobNbErKqw-Gma5lPU

**Comment by kulsoom-abdullah** [comment]
I modified my code to use these rules. 
https://colab.research.google.com/drive/1uKkgcf1Q7XmUejxobNbErKqw-Gma5lPU
This is now using 3 data points, that is, 3 transcripts.
