### ISSUE TITLE
task1_ai_model : Make baseline backend return a multi-label aggregation of model

### ISSUE THREAD

**Issue by nlauchande** [omdena/ptsd#17]
I in the current baseline model we basically have one model for each category. The API frontend of MLFlow by default allow one endpoint per classifier. We might need to create a specialized classifier api front to serve the models.

**Goals**:
- Produce one coherent backend for the multilabel classification most likely by specializing the  serving layer of mlflow.

**Comment by elateifsara** [comment]
@nlauchande I don’t really understand what you mean by this. But how about we do gradual classifications: As in we first classify the client conversation as A1 (0 or 1), then we use that data as input and we determine B1 or the following item. We continue until we give the final output classification which PTSD (0 or 1)?

**Comment by nlauchande** [comment]
@elateifsara : The problem is with the multi-label , multi-classfiication approach with logistic regression that i am following on the baseline model we produce one sklearn model per criterion. So the idea of this task is to unify this issue.
