### ISSUE TITLE
Create a syntetic development dataset of a PTSD transcript to aid on prototyping

### ISSUE THREAD

**Issue by nlauchande** [omdena/ptsd#3]
In order to evaluate tooling and testing we need an initial development dataset just for testing the different tools and algorithms.

This task involves transforming the PDF information available on the transcript in a format better for consumption by machines.

Part of the task is looking at different tools and formats available out there.

**Comment by kulsoom-abdullah** [comment]
This would be parsing PDF documents for the text and/or OCR ?

**Comment by Aya-S** [comment]
Is this task not related to task2_datasets?
are the PTSD transcripts you mention in your task statement an output of task2?

**Comment by nlauchande** [comment]
@Aya-S: Yes this is a dataset kind of task. 

The context of this task is that some of us are playing with this NLU systems for the time being and it sounded a bit realistic for us to try to play with our initial datasets just to get a better feeling of the problem.

**Comment by nlauchande** [comment]
@kulsoom-abdullah : 
I would say most likely the dialogs need to be adapted in a format that is readable by one of the conversational systems that we have around here. 

Some links examples of potential usable dataset formats that I have seen so far :

1. https://blog.rasa.com/designing-rasa-training-stories/

2. https://botsociety.io/features

I think more than an OCR capture we will need to adapt the data to a standard format that NLU systems use.

**Comment by sylvia31096** [comment]
I do not know if this can help out. But this site has examples of transcripts between patients and therapists.
https://www.apa.org/ptsd-guideline/resources/case-examples

**Comment by kulsoom-abdullah** [comment]
I can help, if needed, with parsing the chosen transcripts.

**Comment by nlauchande** [comment]
@kulsoom-abdullah  : Feel free to investigate this . @albertlai431  is trying to get some of our current transcripts into rasa . If keen to work on this you can get in touch w/him.

**Comment by kulsoom-abdullah** [comment]
> @kulsoom-abdullah : Feel free to investigate this . @albertlai431 is trying to get some of our current transcripts into rasa . If keen to work on this you can get in touch w/him.

Sorry for the late reply.  I would prefer to focus on the data work/prep for before it goes into the chatbot, vs getting it into the chatbot.  Though, if you do need help soon, I will try it out.
@albertlai431

**Comment by albertlai431** [comment]
@kulsoom-abdullah Yeah, I've been working on how we can format the data into something the chatbot can understand. However, I believe with the frameworks we have, it might be more suitable to try to build our own model/transfer learning.
